import { ScraperConfig } from "./types";

export const websiteConfigs: Record<string, ScraperConfig> = {
  hubspot: {
    name: "HubSpot Blog",
    url: "https://blog.hubspot.com/marketing",
    selectors: {
      articleContainer: "article",
      title: "h2, h3",
      description: "p",
      author: ".blog-card__author-name, .author-name, [data-author]",
      authorImage: ".author-avatar img, .author-image img",
      date: "time",
      image: "img",
      link: "h2 a, h3 a, a[href*='/marketing/'], a[href*='/sales/'], a[href*='/service/']",
      category: ".post-category, .category, .blog-category",
      tags: ".post-tags a, .tag, .tags a",
    },
    pagination: {
      type: "next-page",
      selector: "a.pagination__link--next",
      maxPages: 10,
    },
  },
  sej: {
    name: "Search Engine Journal",
    url: "https://www.searchenginejournal.com/category/seo/",
    selectors: {
      articleContainer: "article",
      title: "h2",
      description: "p",
      author: ".author-name",
      authorImage: ".author-avatar img, .author-photo img",
      date: "time",
      image: "img",
      link: "h2 a, a[href*='/searchenginejournal.com/']",
      category: ".category, .post-category",
      tags: ".tags a, .post-tags a",
    },
    pagination: {
      type: "next-page",
      selector: "a.next",
      maxPages: 10,
    },
  },
  smashing: {
    name: "Smashing Magazine",
    url: "https://www.smashingmagazine.com/articles/",
    selectors: {
      articleContainer: "article.article--post",
      title: "h1, h2",
      description: "section p",
      author: "a.author-name",
      authorImage: ".author-avatar img, .author-image img",
      date: "time",
      image: "figure img",
      link: "h1 a, h2 a, a[href*='/smashingmagazine.com/']",
      category: ".article-category, .category",
      tags: ".article-tags a, .tags a",
    },
    pagination: {
      type: "next-page",
      selector: "a.next",
      maxPages: 10,
    },
  },
  sitepoint: {
    name: "SitePoint",
    url: "https://www.sitepoint.com/javascript/",
    selectors: {
      articleContainer: ".article-card",
      title: "h2",
      description: "p",
      author: ".author",
      authorImage: ".author-avatar img, .author-photo img",
      date: "time",
      image: "img",
      link: "h2 a, a[href*='/sitepoint.com/']",
      category: ".category, .post-category",
      tags: ".tags a, .post-tags a",
    },
    pagination: {
      type: "next-page",
      selector: ".next",
      maxPages: 10,
    },
  },
  techcrunch: {
    name: "TechCrunch",
    url: "https://techcrunch.com/",
    selectors: {
      articleContainer: "article, .post-block",
      title: "h2 a, .post-block__title a, h2",
      description: "p, .post-block__content, .excerpt",
      author: ".river-byline__authors, .byline__author, .author",
      authorImage: ".author-avatar img, .author-photo img, .avatar img",
      date: "time, [datetime]",
      image: "img",
      link: "h2 a, .post-block__title a, article a",
      category: ".category, .post-category",
      tags: ".tags a, .post-tags a",
    },
    pagination: {
      type: "next-page",
      selector: "a.load-more, .pagination a.next",
      maxPages: 10,
    },
  },
  moz: {
    name: "Moz Blog",
    url: "https://moz.com/blog",
    selectors: {
      articleContainer: "article, .post-item, .blog-post",
      title: "h2 a, h3 a, .post-title a",
      description: "p, .post-excerpt, .post-summary",
      author: ".author-name, .author, .byline",
      authorImage: ".author-avatar img, .author-image img, .author-photo img",
      date: "time, .post-date, [datetime]",
      image: "img",
      link: "h2 a, h3 a, .post-title a, a[href*='/blog/']",
      category: ".post-category, .category, .blog-category",
      tags: ".post-tags a, .tags a, .tag",
    },
    pagination: {
      type: "next-page",
      selector: "a.next, .pagination a.next, .pagination-next",
      maxPages: 10,
    },
  },
  csstricks: {
    name: "CSS-Tricks",
    url: "https://css-tricks.com/archives/",
    selectors: {
      articleContainer: "article, .article-card, .post, .post-item, [class*='article'], [class*='post']",
      title: "h2 a, h3 a, .article-title a, .post-title a, a[href*='/archives/']",
      description: "p, .article-excerpt, .post-excerpt, .summary",
      author: ".author-name, .author, .byline, [class*='author']",
      authorImage: ".author-avatar img, .author-image img, .author-photo img, [class*='author'] img",
      date: "time, .post-date, [datetime], [class*='date']",
      image: "img",
      link: "h2 a, h3 a, .article-title a, .post-title a, a[href*='/archives/']:not([href*='/archives/page/'])",
      category: ".post-category, .category, .article-category, [class*='category']",
      tags: ".post-tags a, .tags a, .tag, [class*='tag'] a",
    },
    pagination: {
      type: "page-number",
      maxPages: 10,
    },
  },
  webdev: {
    name: "Web.dev",
    url: "https://web.dev/blog/",
    selectors: {
      articleContainer: "article, .post-card, .blog-post",
      title: "h2 a, h3 a, .post-title a",
      description: "p, .post-excerpt, .post-summary",
      author: ".author-name, .author, .byline",
      authorImage: ".author-avatar img, .author-image img, .author-photo img",
      date: "time, .post-date, [datetime]",
      image: "img",
      link: "h2 a, h3 a, .post-title a, a[href*='/blog/']",
      category: ".post-category, .category, .blog-category",
      tags: ".post-tags a, .tags a, .tag",
    },
    pagination: {
      type: "next-page",
      selector: "a.next, .pagination a.next, .pagination-next",
      maxPages: 10,
    },
  },
};
